/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/**
 * Safe initializer for the Rust side, hooking a panic logger.
 * We only call `INIT.call_once(...)` to ensure it’s done once.
 */
export declare function safeInitRust(): void
